phrase:
  access_token: a7e77b9e0c31ca4f5a941d75c40928120fff462ba59fa383bcd8fa5b3ae39334
  project_id: f9497c2f433e3067f24d3ffcda2daac7
  push:
    sources:
      - file: ./assets/i18n/fr.json
        params:
          file_format: simple_json
  pull:
    targets:
      - file: ./assets/i18n/fr.json
        params:
          file_format: simple_json
