# Yarn config file
# @see https://yarnpkg.com/configuration/yarnrc

# Yarn cache compression level
compressionLevel: mixed

# prevent adding "^" or "~" when using `yarn add`
defaultSemverRangePrefix: ''

# Yarn cache is local, stored in .yarn/cache
enableGlobalCache: false

# Print build log when using `yarn install`
enableInlineBuilds: true

# Store intalled packages in node-module the old way
nodeLinker: node-modules
