#!/usr/bin/env node

"use strict";


const fr = require("./assets/i18n/fr")

process.stdout.write( '/*** Fichier généré automatiquement par "npm run lang" ***/\n')
process.stdout.write( '/*** Ne pas modifier ***/\n\n')

process.stdout.write( `export const keyTrans = (I18n) => ({\n`)

const tr = Object.entries(fr).map( (elem) => process.stdout.write( `   ${elem[0]} : I18n.t("${elem[0]}"),\n`))

process.stdout.write( `})`)



