import { PixelRatio } from 'react-native'

export const layoutSize = {
  LAYOUT_0: PixelRatio.getPixelSizeForLayoutSize(0),
  LAYOUT_1: PixelRatio.getPixelSizeForLayoutSize(1),
  LAYOUT_2: PixelRatio.getPixelSizeForLayoutSize(2),
  LAYOUT_3: PixelRatio.getPixelSizeForLayoutSize(3),
  LAYOUT_4: PixelRatio.getPixelSizeForLayoutSize(4),
  LAYOUT_5: PixelRatio.getPixelSizeForLayoutSize(5),
  LAYOUT_6: PixelRatio.getPixelSizeForLayoutSize(6),
  LAYOUT_7: PixelRatio.getPixelSizeForLayoutSize(7),
  LAYOUT_8: PixelRatio.getPixelSizeForLayoutSize(8),
  LAYOUT_9: PixelRatio.getPixelSizeForLayoutSize(9),
  LAYOUT_10: PixelRatio.getPixelSizeForLayoutSize(10),
  LAYOUT_11: PixelRatio.getPixelSizeForLayoutSize(11),
  LAYOUT_12: PixelRatio.getPixelSizeForLayoutSize(12),
  LAYOUT_13: PixelRatio.getPixelSizeForLayoutSize(13),
  LAYOUT_14: PixelRatio.getPixelSizeForLayoutSize(14),
  LAYOUT_15: PixelRatio.getPixelSizeForLayoutSize(15),
  LAYOUT_16: PixelRatio.getPixelSizeForLayoutSize(16),
  LAYOUT_20: PixelRatio.getPixelSizeForLayoutSize(20),
  LAYOUT_22: PixelRatio.getPixelSizeForLayoutSize(22),
  LAYOUT_23: PixelRatio.getPixelSizeForLayoutSize(23),
  LAYOUT_24: PixelRatio.getPixelSizeForLayoutSize(24),
  LAYOUT_25: PixelRatio.getPixelSizeForLayoutSize(25),
  LAYOUT_28: PixelRatio.getPixelSizeForLayoutSize(28),
  LAYOUT_30: PixelRatio.getPixelSizeForLayoutSize(30),
  LAYOUT_31: PixelRatio.getPixelSizeForLayoutSize(31),
  LAYOUT_32: PixelRatio.getPixelSizeForLayoutSize(32),
  LAYOUT_36: PixelRatio.getPixelSizeForLayoutSize(36),
  LAYOUT_40: PixelRatio.getPixelSizeForLayoutSize(40),
  LAYOUT_42: PixelRatio.getPixelSizeForLayoutSize(42),
  LAYOUT_50: PixelRatio.getPixelSizeForLayoutSize(50),
  LAYOUT_60: PixelRatio.getPixelSizeForLayoutSize(60),
  LAYOUT_62: PixelRatio.getPixelSizeForLayoutSize(62),
  LAYOUT_70: PixelRatio.getPixelSizeForLayoutSize(70),
  LAYOUT_75: PixelRatio.getPixelSizeForLayoutSize(75),
  LAYOUT_80: PixelRatio.getPixelSizeForLayoutSize(80),
  LAYOUT_90: PixelRatio.getPixelSizeForLayoutSize(90),
  LAYOUT_100: PixelRatio.getPixelSizeForLayoutSize(100),
  LAYOUT_110: PixelRatio.getPixelSizeForLayoutSize(110),
  LAYOUT_120: PixelRatio.getPixelSizeForLayoutSize(120),
  LAYOUT_140: PixelRatio.getPixelSizeForLayoutSize(140),
  LAYOUT_160: PixelRatio.getPixelSizeForLayoutSize(160),
  LAYOUT_200: PixelRatio.getPixelSizeForLayoutSize(200),
}
