/**
 * ODE Mobile UI - Icon
 * Get icon components from the custom icon font generated by Icomoon.
 */
import { TextProps } from 'react-native';

import { createIconSetFromIcoMoon } from 'react-native-vector-icons';

const icoMoonConfig = require('ASSETS/selection.json');

/**
 * @deprecated Use ~/framework/components/picture/Icon instead.
 */
export const Icon = createIconSetFromIcoMoon(icoMoonConfig);

export const checkHasIcon = (name: string) => Icon.hasIcon(name);

export interface IconProps extends TextProps {
  color?: any;
  focused?: boolean;
  name?: string;
  paddingHorizontal?: number;
  size?: number;
}
