export const actions = {
  alignCenter: 'justifyCenter',
  alignFull: 'justifyFull',
  alignLeft: 'justifyLeft',
  alignRight: 'justifyRight',
  checkboxList: 'checkboxList',
  content: 'content',
  fontName: 'fontName',
  fontSize: 'fontSize',
  heading1: 'heading1',
  heading2: 'heading2',
  heading3: 'heading3',
  heading4: 'heading4',
  heading5: 'heading5',
  heading6: 'heading6',
  code: 'code',
  indent: 'indent',
  insertBulletsList: 'unorderedList',
  insertHTML: 'html',
  foreColor: 'foreColor',
  setBold: 'bold',
  blockquote: 'quote',
  setItalic: 'italic',
  hiliteColor: 'hiliteColor',
  setUnderline: 'underline',
  insertLine: 'line',
  insertOrderedList: 'orderedList',
  insertText: 'text',
  keyboard: 'keyboard',
  line: 'line',
  removeFormat: 'removeFormat',
  outdent: 'outdent',
  setParagraph: 'paragraph',
  init: 'init',
  prepareInsert: 'PREPARE_INSERT',
  redo: 'redo',
  restoreSelection: 'RESTORE_SELECTION',
  selection: 'selection',
  setBackgroundColor: 'SET_BACKGROUND_COLOR',
  setContentFocusHandler: 'SET_CONTENT_FOCUS_HANDLER',
  setContentPlaceholder: 'SET_CONTENT_PLACEHOLDER',
  setCustomCSS: 'SET_CUSTOM_CSS',
  setStrikethrough: 'strikeThrough',
  setEditorHeight: 'SET_EDITOR_HEIGHT',
  setSubscript: 'subscript',
  setFooterHeight: 'SET_FOOTER_HEIGHT',
  setSuperscript: 'superscript',
  setHR: 'horizontalRule',
  setPlatform: 'SET_PLATFORM',
  setTextColor: 'SET_TEXT_COLOR',
  setTitleFocusHandler: 'SET_TITLE_FOCUS_HANDLER',
  undo: 'undo',
  setTitlePlaceholder: 'SET_TITLE_PLACEHOLDER',
  table: 'table',
};

export const messages = {
  AUDIO_TOUCHED: 'AUDIO_TOUCHED',
  CONTENT_BLUR: 'CONTENT_BLUR',
  CONTENT_CHANGE: 'CONTENT_CHANGE',
  CONTENT_FOCUSED: 'CONTENT_FOCUSED',
  CONTENT_HTML_RESPONSE: 'CONTENT_HTML_RESPONSE',
  CONTENT_KEYDOWN: 'CONTENT_KEYDOWN',
  CONTENT_KEYUP: 'CONTENT_KEYUP',
  CONTENT_PASTED: 'CONTENT_PASTED',
  IMAGE_TOUCHED: 'IMAGE_TOUCHED',
  IMAGES_URLS: 'IMAGES_URLS',
  LINK_TOUCHED: 'LINK_TOUCHED',
  LINKS_URLS: 'LINKS_URLS',
  LOG: 'LOG',
  OFFSET_HEIGHT: 'OFFSET_HEIGHT',
  OFFSET_Y: 'OFFSET_Y',
  ON_INPUT: 'ON_INPUT',
  SELECTED_TEXT_CHANGED: 'SELECTED_TEXT_CHANGED',
  SELECTED_TEXT_RESPONSE: 'SELECTED_TEXT_RESPONSE',
  SELECTION_CHANGE: 'SELECTION_CHANGE',
  VIDEO_TOUCHED: 'VIDEO_TOUCHED',
};

export const ui = {
  image: {
    class: 'custom-image',
    height: 'NaN',
    width: 250,
  },
  insertElementTimeout: 100,
  updateHeightTimeout: 1000,
};
