require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'appe' do

  config = use_native_modules!
  flags = get_default_flags()
  $RNFirebaseAsStaticFramework = true

  #
  # Static libraries => use modular headers
  #
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  #
  # react-native-permissions : @see: https://github.com/zoontek/react-native-permissions#ios
  #
  permissions_path = '../node_modules/react-native-permissions/ios'
  #pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  #pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  #pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  #pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  #pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  #pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  #pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  #pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  #pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  #pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  #pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  #pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  #pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  #pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

  #
  # react-native-text-sizze not added automatically
  #
  pod 'RNTextSize', :path => "../node_modules/react-native-text-size/ios"

  #
  # React Native Stuff
  #
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
