const saasCommon = {
  oauth: ["app-e", "yTFxAPupNnKb9VcKwA6E5DA3"],
};

module.exports = {
  // ONE
  "preprod-one": {
    ...saasCommon,
    name: "preprod-one",
    url: "https://preprod-oneconnect.edifice.io",
    logo: require("ASSETS/platforms/logo-one.png"),
    displayName: "Préprod ONE",
    webTheme: "oneconnect",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-one": {
    ...saasCommon,
    name: "prod-one",
    url: "https://oneconnect.edifice.io",
    logo: require("ASSETS/platforms/logo-one.png"),
    displayName: "ONE",
    webTheme: "oneconnect",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // NEO
  "preprod-neo": {
    ...saasCommon,
    name: "preprod-neo",
    url: "https://preprod-neoconnect.edifice.io",
    logo: require("ASSETS/platforms/logo-neo.png"),
    displayName: "Préprod NEO",
    webTheme: "neoconnect",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-neo": {
    ...saasCommon,
    name: "prod-neo",
    url: "https://neoconnect.edifice.io",
    logo: require("ASSETS/platforms/logo-neo.png"),
    displayName: "NEO",
    webTheme: "neoconnect",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // e-primo
  "preprod-e-primo": {
    ...saasCommon,
    name: "preprod-e-primo",
    url: "https://preprod.e-primo.fr",
    logo: require("ASSETS/platforms/logo-e-primo.png"),
    displayName: "Préprod e-primo",
    webTheme: "nantes1d",
    splashads: "https://edifice.io/mobile/splashads/eprimo",
  },
  "prod-e-primo": {
    ...saasCommon,
    name: "prod-e-primo",
    url: "https://ent.e-primo.fr",
    logo: require("ASSETS/platforms/logo-e-primo.png"),
    displayName: "e-primo",
    webTheme: "nantes1d",
    wayf: "https://ent.e-primo.fr/auth/saml/wayf?callback=https%3A%2F%2Fent.e-primo.fr%2F#/",
    splashads: "https://edifice.io/mobile/splashads/eprimo",
  },

  // Ari@ne.57
  "preprod-ariane": {
    ...saasCommon,
    name: "preprod-ariane-57",
    url: "https://preprod-ariane57.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-ariane-57.png"),
    displayName: "Préprod Ari@ne57",
    webTheme: "moselle1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-ariane": {
    ...saasCommon,
    name: "prod-ariane-57",
    url: "https://ariane57.moselle-education.fr",
    logo: require("ASSETS/platforms/logo-ariane-57.png"),
    displayName: "Ari@ne57",
    webTheme: "moselle1d",
    wayf: "https://ariane57.moselle-education.fr/connexion",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Mayotte
  "preprod-mayotte": {
    ...saasCommon,
    name: "preprod-mayotte",
    url: "https://preprod-mayotte.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-mayotte.png"),
    displayName: "Préprod ENT Mayotte",
    webTheme: "neoconnect",
    splashads: "https://edifice.io/mobile/splashads/neo",
    // No wayf in preprod
  },
  "prod-mayotte": {
    ...saasCommon,
    name: "prod-mayotte",
    url: "https://mayotte.edifice.io",
    logo: require("ASSETS/platforms/logo-mayotte.png"),
    displayName: "ENT Mayotte",
    webTheme: "neoconnect",
    wayf: "https://mayotte.edifice.io/auth/saml/wayf#/",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Wilapa
  "preprod-wilapa": {
    ...saasCommon,
    name: "preprod-wilapa",
    url: "https://preprod-wilapa.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-wilapa.png"),
    displayName: "Préprod Wilapa by NEO",
    webTheme: "guyane",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-wilapa": {
    ...saasCommon,
    name: "prod-wilapa",
    url: "https://wilapa-guyane.com",
    logo: require("ASSETS/platforms/logo-wilapa.png"),
    displayName: "Wilapa by NEO",
    webTheme: "guyane",
    wayf: "https://wilapa-guyane.com/auth/saml/wayf?callback=https%3A%2F%2Fwilapa-guyane.com%2F#/",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "preprod-wilapa-one": {
    ...saasCommon,
    name: "preprod-wilapa-one",
    url: "https://preprod-wilapa.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-wilapa-one.png"),
    displayName: "Préprod Wilapa by ONE",
    webTheme: "guyane1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-wilapa-one": {
    ...saasCommon,
    name: "prod-wilapa-one",
    url: "https://wilapa-guyane.com",
    logo: require("ASSETS/platforms/logo-wilapa-one.png"),
    displayName: "Wilapa by ONE",
    webTheme: "guyane1d",
    wayf: "https://wilapa-guyane.com/auth/saml/wayf?callback=https%3A%2F%2Fwilapa-guyane.com%2F#/",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Toulon
  "preprod-toulon": {
    ...saasCommon,
    name: "preprod-toulon",
    url: "https://toulon.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-toulon.png"),
    displayName: "Préprod ENT Toulon",
    webTheme: "toulon1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-toulon": {
    ...saasCommon,
    name: "prod-toulon",
    url: "https://ent.toulon.fr",
    logo: require("ASSETS/platforms/logo-toulon.png"),
    displayName: "ENT Toulon",
    webTheme: "toulon1d",
    wayf: "https://ent.toulon.fr/auth/saml/wayf?callback=https%3A%2F%2Fent.toulon.fr%2F#/",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Var
  "preprod-var": {
    ...saasCommon,
    name: "preprod-var",
    url: "https://entvar.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-var.png"),
    displayName: "Préprod ENT Var",
    webTheme: "var2d",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-var": {
    ...saasCommon,
    name: "prod-var",
    url: "https://moncollege-ent.var.fr",
    logo: require("ASSETS/platforms/logo-var.png"),
    displayName: "ENT Var",
    webTheme: "var2d",
    wayf: "https://moncollege-ent.var.fr/auth/saml/wayf?callback=https%3A%2F%2Fmoncollege-ent.var.fr%2F#/",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Porto-Vecchio
  "preprod-porto-vecchio": {
    ...saasCommon,
    name: "preprod-porto-vecchio",
    url: "https://preprod-portivechju.edifice.io",
    logo: require("ASSETS/platforms/logo-porto-vecchio.png"),
    displayName: "Préprod Porto-Vecchio",
    webTheme: "portovecchio",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-porto-vecchio": {
    ...saasCommon,
    name: "prod-porto-vecchio",
    url: "https://portivechju.edifice.io",
    logo: require("ASSETS/platforms/logo-porto-vecchio.png"),
    displayName: "Porto-Vecchio",
    //wayf: "https://portivechju.edifice.io/auth/saml/wayf?#",
    webTheme: "portovecchio",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Reims
  "preprod-reims": {
    ...saasCommon,
    name: "preprod-reims",
    url: "https://preprod-reims.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-reims.png"),
    displayName: "Préprod ENT Écoles Académie Reims",
    webTheme: "reims",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-reims": {
    ...saasCommon,
    name: "prod-reims",
    url: "https://ent-ecoles.ac-reims.fr",
    logo: require("ASSETS/platforms/logo-reims.png"),
    displayName: "ENT Écoles Académie Reims",
    wayf: "https://ent-ecoles.ac-reims.fr/auth/saml/wayf?#/",
    webTheme: "reims",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Vienne Condrieu
  "preprod-vienne-condrieu": {
    ...saasCommon,
    name: "preprod-vienne-condrieu",
    url: "https://preprod-vca.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-vienne-condrieu.png"),
    displayName: "Préprod VCA",
    webTheme: "vca",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-vienne-condrieu": {
    ...saasCommon,
    name: "prod-vienne-condrieu",
    url: "https://ent.vienne-condrieu-agglomeration.fr",
    logo: require("ASSETS/platforms/logo-vienne-condrieu.png"),
    displayName: "Vienne Condrieu Agglomération",
    wayf: "https://ent.vienne-condrieu-agglomeration.fr/auth/saml/wayf?#/",
    webTheme: "vca",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Hautes Alpes
  "preprod-hautes-alpes": {
    ...saasCommon,
    name: "preprod-hautes-alpes",
    url: "https://ent05.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-hautes-alpes.png"),
    displayName: "Préprod ENT Hautes-Alpes",
    webTheme: "ent05",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-hautes-alpes": {
    ...saasCommon,
    name: "prod-hautes-alpes",
    url: "https://ent.colleges05.fr",
    logo: require("ASSETS/platforms/logo-hautes-alpes.png"),
    displayName: "ENT Hautes-Alpes",
    wayf: "https://ent.colleges05.fr/auth/saml/wayf#/",
    webTheme: "ent05",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // La Polynésie (Natitahi & Natirua)
  // 1D
  "preprod-natitahi": {
    ...saasCommon,
    name: "preprod-natitahi",
    url: "https://preprod-nati.edifice.io",
    logo: require("ASSETS/platforms/logo-natitahi.png"),
    displayName: "Préprod natitahi",
    webTheme: "nati1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-natitahi": {
    ...saasCommon,
    name: "prod-natitahi",
    url: "https://nati.pf",
    logo: require("ASSETS/platforms/logo-natitahi.png"),
    displayName: "Natitahi",
    wayf: "https://nati.pf/assets/cgu/nati_wayf.html",
    webTheme: "nati1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  // 2D
  "preprod-natirua": {
    ...saasCommon,
    name: "preprod-natirua",
    url: "https://preprod-nati.edifice.io",
    logo: require("ASSETS/platforms/logo-natirua.png"),
    displayName: "Préprod natirua",
    webTheme: "nati2d",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-natirua": {
    ...saasCommon,
    name: "prod-natirua",
    url: "https://nati.pf",
    logo: require("ASSETS/platforms/logo-natirua.png"),
    displayName: "Natirua",
    wayf: "https://nati.pf/assets/cgu/nati_wayf.html",
    webTheme: "nati2d",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Nice
  "preprod-nice": {
    ...saasCommon,
    name: "preprod-nice",
    url: "https://preprod-nice.edifice.io",
    logo: require("ASSETS/platforms/logo-nice.png"),
    displayName: "Préprod ENT Nice",
    webTheme: "nice",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-nice": {
    ...saasCommon,
    name: "prod-nice",
    url: "https://ent.nice.fr",
    logo: require("ASSETS/platforms/logo-nice.png"),
    displayName: "ENT Nice",
    wayf: "https://ent.nice.fr/auth/saml/wayf?#/",
    webTheme: "nice",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Bouche du rhône
  "preprod-eduprovence": {
    ...saasCommon,
    name: "preprod-eduprovence",
    url: "https://preprod-cd13.edifice.io",
    logo: require("ASSETS/platforms/logo-eduprovence.png"),
    displayName: "Préprod EduProvence",
    wayf: "https://preprod-cd13.edifice.io/auth/saml/wayf",
    webTheme: "cd13",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-eduprovence": {
    ...saasCommon,
    name: "prod-eduprovence",
    url: "https://www.eduprovence.fr",
    logo: require("ASSETS/platforms/logo-eduprovence.png"),
    displayName: "EduProvence",
    wayf: "https://www.eduprovence.fr/auth/saml/wayf",
    webTheme: "cd13",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Charente
  "preprod-charente": {
    ...saasCommon,
    name: "preprod-charente",
    url: "https://preprod-ent16.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-charente.png"),
    displayName: "Préprod La Charente",
    webTheme: "cd16",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-charente": {
    ...saasCommon,
    name: "prod-charente",
    url: "https://mon-ent16.lacharente.fr",
    logo: require("ASSETS/platforms/logo-charente.png"),
    displayName: "La Charente",
    wayf: "https://mon-ent16.lacharente.fr/auth/saml/wayf",
    webTheme: "cd16",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Vosges
  "preprod-panda-vosges": {
    ...saasCommon,
    name: "preprod-panda-vosges",
    url: "https://preprod-vosges.edifice.io",
    logo: require("ASSETS/platforms/logo-panda-vosges.png"),
    displayName: "Préprod PANDA Vosges",
    webTheme: "vosges",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-panda-vosges": {
    ...saasCommon,
    name: "prod-panda-vosges",
    url: "https://panda.vosges.fr",
    logo: require("ASSETS/platforms/logo-panda-vosges.png"),
    displayName: "PANDA Vosges",
    wayf: "https://panda.vosges.fr/auth/saml/wayf",
    webTheme: "vosges",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // ENT04
  "preprod-ent04": {
    ...saasCommon,
    name: "preprod-ent04",
    url: "https://preprod.ent04.fr",
    logo: require("ASSETS/platforms/logo-ent04.png"),
    displayName: "Préprod ENT04",
    webTheme: "ent04",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-ent04": {
    ...saasCommon,
    name: "prod-ent04",
    url: "https://ent04.fr",
    logo: require("ASSETS/platforms/logo-ent04.png"),
    displayName: "ENT04",
    wayf: "https://ent04.fr/auth/saml/wayf",
    webTheme: "ent04",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },

  // Créteil
  "preprod-creteil": {
    ...saasCommon,
    name: "preprod-creteil",
    url: "https://preprod.ac-creteil.edifice.io",
    logo: require("ASSETS/platforms/logo-creteil.png"),
    displayName: "Préprod Créteil",
    webTheme: "creteil",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-creteil": {
    ...saasCommon,
    name: "prod-creteil",
    url: "https://ressourcesecole-creteil.edifice.io",
    logo: require("ASSETS/platforms/logo-creteil.png"),
    displayName: "Créteil",
    wayf: "https://ressourcesecole-creteil.edifice.io/auth/saml/wayf",
    webTheme: "creteil",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // E-cléo
  "preprod-ecleo": {
    ...saasCommon,
    name: "preprod-ecleo",
    url: "https://preprod-sem.opendigitaleducation.com",
    logo: require("ASSETS/platforms/logo-ecleo.png"),
    displayName: "Préprod E-cléo",
    webTheme: "oneconnect",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-ecleo": {
    ...saasCommon,
    name: "prod-ecleo",
    url: "https://sem.edifice.io",
    logo: require("ASSETS/platforms/logo-ecleo.png"),
    displayName: "E-cléo",
    wayf: "https://sem.edifice.io/auth/saml/wayf",
    webTheme: "oneconnect",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Corse
  "preprod-corse": {
    ...saasCommon,
    displayName: "Préprod ONE Corsica",
    logo: require("ASSETS/platforms/logo-corse-one.png"),
    name: "preprod-corse",
    splashads: "https://edifice.io/mobile/splashads/one",
    url: "https://preprod-one-corsica.edifice.io",
    webTheme: "corse1d",
  },
  "prod-corse": {
    ...saasCommon,
    displayName: "ONE Corsica",
    logo: require("ASSETS/platforms/logo-corse-one.png"),
    name: "prod-corse",
    splashads: "https://edifice.io/mobile/splashads/one",
    url: "https://one-corsica.edifice.io",
    webTheme: "corse1d",
  },

  // Starsbourg
  "preprod-strasbourg-one": {
    ...saasCommon,
    name: "preprod-strasbourg-one",
    url: "https://preprod-strasbourg.edifice.io",
    logo: require("ASSETS/platforms/logo-strasbourg-one.png"),
    displayName: "Préprod Écoles Ac. Strasbourg",
    webTheme: "strasbourg1d",
    splashads: "https://edifice.io/mobile/splashads/one",
  },
  "prod-strasbourg-one": {
    ...saasCommon,
    name: "prod-strasbourg-one",
    url: "https://wilapa-guyane.com",
    logo: require("ASSETS/platforms/logo-strasbourg-one.png"),
    displayName: "Écoles Ac. Strasbourg",
    webTheme: "strasbourg1d",
    //wayf: "https://wilapa-guyane.com/auth/saml/wayf?callback=https%3A%2F%2Fwilapa-guyane.com%2F#/",
    splashads: "https://edifice.io/mobile/splashads/one",
  },

  // Vaucluse
  "preprod-vaucluse": {
    ...saasCommon,
    name: "preprod-vaucluse",
    url: "https://preprod-essonne.entcore.org",
    logo: require("ASSETS/platforms/logo-vaucluse.png"),
    displayName: "Préprod Au collège 84",
    webTheme: "vaucluse",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
  "prod-vaucluse": {
    ...saasCommon,
    name: "prod-vaucluse",
    url: "https://www.aucollege84.vaucluse.fr",
    logo: require("ASSETS/platforms/logo-vaucluse.png"),
    displayName: "Au collège 84",
    wayf: "https://www.aucollege84.vaucluse.fr/auth/saml/wayf?callback=https%3A%2F%2Fwww.aucollege84.vaucluse.fr%2F#/",
    webTheme: "vaucluse",
    splashads: "https://edifice.io/mobile/splashads/neo",
  },
};
