export const CommonStyles = {
	actionColor: "#2A9CC8",
	actionColorDisabled: "#2A9CC888",
	backgroundColor: "#F8F8FA",
	entryfieldBorder: "#DCDDE0",
	buttonColor: "#ffffff",
	borderColor: "#cccccc",
	borderColorLighter: "#e2e2e2",
	cardTitle: "#1467ff",
	elevation: 20,
	errorColor: "red",
	fadColor: "#444444",
	iconColorOff: "#858FA9",
	iconColorOn: "#2A9CC8",
	inputBackColor: "#F8F8FA",
	inverseColor: "#F8F8FA",
	linkColor: "#2a97f5",
	mainColorTheme: "#2A9CC8",
	placeholderColor: "#B2BECDDD",
	miniTextColor: "#858FA9",
	primaryBorderColor: "#bcbbc1", // some grey-ish delight with a touch of lavender. Amazing.
	primaryButtonColor: "#007396", //blue-ish theme
	primaryFontFamily: "OpenSans",
	primaryFontFamilyBold: "OpenSans-bold",
	primaryFontFamilySemibold: "OpenSans-semibold",
	primaryFontFamilyLight: "OpenSans-light",
	primaryTitleColor: "#007396", //blue-ish theme
	secondaryBackGroundColor: "#f9fafb",
	secondaryButtonColor: "#fc624d", //red-ish theme
	secondaryFontColor: "#8e8e93",
	selectColor: "#ffff00",
	shadowColor: "rgba(0, 0, 0, 1.0)",
	shadowOffset: {
		width: 0,
		height: 1,
	},
	shadowOpacity: 0.25,
	shadowRadius: 4,
	tabBottomColor: "#ffffff",
	textColor: "#414355",
	textInputColor: "#414355",
	textTabBottomColor: "#858FA9",
	titleColor: "#1467ff",
	tabBackgroundColor: "#2a97f5",
}
