export default [
  require('~/modules/blog'),
  require('~/modules/conversation'),
  require('~/modules/lvs'),
  require('~/modules/mediacentre'),
  require('~/modules/news'),
  require('~/modules/pronote'),
  require('~/modules/schoolbook'),
  require('~/modules/support'),
  require('~/modules/viescolaire/competences'),
  require('~/modules/viescolaire/edt'),
  require('~/modules/viescolaire/dashboard'),
  require('~/modules/viescolaire/diary'),
  require('~/modules/viescolaire/presences'),
  require('~/modules/workspace'),
  require('~/modules/zimbra'),
];
