name: Merge phrase-translations

on:
  pull_request:
    branches:
      - phrase-translations

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto Merge Pull Request
        uses: pascalgn/automerge-action@v0.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
          MERGE_LABELS: ''
          MERGE_METHOD: 'squash'

      - name: Slack Notification on error
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Merge phrase-translations completed : ${{ job.status }}'
          SLACK_TITLE: 'Merge phrase-translations'
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
