name: Merge phrase-translations

on:
  pull_request:
    branches:
      - phrase-translations

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto Merge Pull Request
        uses: pascalgn/automerge-action@v0.11.0
        with:

        env:
          BASE_BRANCHES: "phrase-translations"
          GITHUB_TOKEN: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"

      - name: Send Slack notification on failure
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
