name: Sync phrase-translations

on:
  push:
    branches:
      - dev/1.12.0

jobs:
  sync-branch:
    name: Sync phrase-translations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: connor-baer/action-sync-branch@main
        with:
          branch: phrase-translations
          token: ${{ secrets.PHRASE_TRANSLATIONS }}
          force: true

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          message: "Sync phrase-translations completed: ${{ job.status }}"
          action_result: ${{ job.status }}
          color: ${{ job.status === 'success' ? '#9ECCFF' : '#F4887C' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
