name: Sync phrase-translations

on:
  push:
    branches:
      - dev/1.12.0

jobs:
  sync-branch:
    name: Sync phrase-translations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: connor-baer/action-sync-branch@main
        with:
          branch: phrase-translations
          token: ${{ secrets.PHRASE_TRANSLATIONS }}
          force: true

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Sync phrase-translations completed",
              "attachments": [
                {
                  "pretext": "${{ job.status }}",
                  "color": "9ECCFF"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MONITOR_MOBILE_URL }}
